version: "3.8"


services:
    db:
        image: postgres
        restart: always
        env_file:
            - ./backend/.env
        ports:
            - "5432:5432"
    backend:
        build: ./backend
        volumes:
            - ./backend:/app/backend
        env_file:
            - ./backend/.env
        command: python3 manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        stdin_open: true
        tty: true
        depends_on:
            - db
#    frontend:
#        build: ./frontend
#        volumes:
#            - ./frontend:/app
#        ports:
#            - "3000:3000"
#        environment:
#            - NODE_ENV=development
#        command: npm start
#        depends_on:
#            - backend
