FROM python:3.8


ENV PYTHONUNBUFFERED 1
ENV PYTHONDONOTWRITEBYTECODE 1


WORKDIR /app/backend



COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

RUN apt-get -q update && apt-get -qy install netcat

# wait tool for scheduling containers
COPY wait-for.sh wait-for.sh
RUN chmod +x wait-for.sh


COPY . /app/backend/



EXPOSE 8000

