FROM python:3.8


ENV PYTHONUNBUFFERED 1
ENV PYTHONDONOTWRITEBYTECODE 1


WORKDIR /app/backend



COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . /app/backend/

RUN useradd user
USER user

EXPOSE 8000


CMD python3 manage.py runserver 0.0.0.0:8000
