# Generated by Django 3.1.5 on 2021-02-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('address', models.CharField(max_length=30)),
                ('needy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.needy')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Announcements.announcement')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Members.volunteer')),
            ],
        ),
    ]
